services:
  - type: web
    name: earth-nights-api
    env: node
    buildCommand: npm install && npm run build && node dist/setupDatabase.js && node dist/resetAndLoadDatabase.js
    startCommand: npm start
    envVars:
      - key: PG_USER
        sync: false
      - key: PG_PASSWORD
        sync: false
      - key: PG_HOST
        sync: false
      - key: PG_PORT
        value: 5432
      - key: PG_DATABASE
        sync: false
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://earth-nights-frontend.onrender.com